#!/usr/bin/sh

$HOME/.config/bspwm/autostart.sh


#BSPWM configuration
bspc config border_width         1
bspc config window_gap           5
bspc config top_padding          25
bspc config bottom_padding       10
bspc config left_padding         10
bspc config right_padding        10
bspc config single_monocle       false
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config normal_border_color		"#c8bd5ca" #teal
bspc config active_border_color		"#b7bdf8" #lavender
bspc config focused_border_color	"#c6a0f6" #mauve
bspc config urgent_border_color 	"#ed8796" #red

bspc monitor -d 1 2 3 4 5 6 7 8 9 10